CREATE DATABASE chatapp;
\c chatapp;

DROP TABLE users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    PROFILE_IMG_URL VARCHAR(256),
    FULL_NAME VARCHAR(256),
    USERNAME VARCHAR(64) UNIQUE NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    BIO VARCHAR(256),
    SOCKET_ID VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);


DROP TABLE messages CASCADE;
CREATE TABLE IF NOT EXISTS messages (
    ID SERIAL PRIMARY KEY,
    FROM_USER_ID INTEGER REFERENCES users(ID),
    TO_USER_ID INTEGER REFERENCES users(ID),
    MESSAGE VARCHAR(2048) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

DROP TABLE statuses CASCADE;
CREATE TYPE STATUS_ENUM AS ENUM ('ONLINE', 'OFFLINE');
CREATE TABLE IF NOT EXISTS statuses (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES users(ID),
    STATUS STATUS_ENUM NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password) values ('blvckeasy', 'islom1234');
INSERT INTO users (username, password) values ('ivan', 'gryaz123');

INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (1, 2, 'HELLO');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (2, 1, 'HI');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (1, 2, 'WHAT IS YOUR NAME ?');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (2, 1, 'WHAT ?');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (1, 2, 'WHAT IS YOUR NAME');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (2, 1, 'MY NAME IS TONY');
INSERT INTO messages (FROM_USER_ID, TO_USER_ID, MESSAGE) VALUES (1, 2, 'NICE TOO MEET YOU');